# Generated by Django 2.2 on 2020-12-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DETAI',
            fields=[
                ('IdDeTai', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('IdUser', models.IntegerField()),
                ('ChiTiet', models.CharField(max_length=1000)),
                ('NgayBD', models.DateTimeField()),
                ('NgayKT', models.DateTimeField()),
                ('SoLuong', models.IntegerField(default=2)),
                ('IdLoai', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DETAIDADANGKY',
            fields=[
                ('IdDTDDK', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('IdDeTai', models.IntegerField()),
                ('IdUser', models.IntegerField()),
                ('NgayDKDT', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DIADIEM',
            fields=[
                ('IdDiaDiem', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('TenDiaDiem', models.CharField(max_length=100)),
                ('ChiTiet', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='GIAITHUONG',
            fields=[
                ('IdGiaiThuong', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('TenGiaiThuong', models.CharField(max_length=100)),
                ('ChiTiet', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='HOATDONG',
            fields=[
                ('IdHoatDong', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('IdUser', models.IntegerField()),
                ('ChiTiet', models.CharField(max_length=1000)),
                ('NgayBD', models.DateTimeField()),
                ('NgayKT', models.DateTimeField()),
                ('SoLuong', models.IntegerField(default=50)),
                ('IdDiaDiem', models.IntegerField()),
                ('IdGiaiThuong', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HOATDONGDADANGKY',
            fields=[
                ('IdHDDDK', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('IdHoatDong', models.IntegerField()),
                ('IdUser', models.IntegerField()),
                ('NgayDKHD', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LOAIDETAI',
            fields=[
                ('IdLoai', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('TenLoai', models.CharField(max_length=100)),
                ('DiemSan', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NGUOIDUNG',
            fields=[
                ('IdUser', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('HoTen', models.CharField(max_length=200)),
                ('MatKhau', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Quyen', models.IntegerField()),
                ('SDT', models.CharField(max_length=15, null=True)),
                ('NgaySinh', models.DateTimeField(null=True)),
                ('GioiTinh', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='THONGBAO',
            fields=[
                ('IdThongBao', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('IdUser', models.IntegerField()),
                ('ChiTiet', models.CharField(max_length=1000)),
                ('NgayThongBao', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
