# Generated by Django 2.2 on 2020-12-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20201205_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='MSSV',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
