# Generated by Django 2.2 on 2020-12-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_nguoidung_hoatdong'),
    ]

    operations = [
        migrations.AddField(
            model_name='detai',
            name='HoatDong',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hoatdong',
            name='HoatDong',
            field=models.BooleanField(default=True),
        ),
    ]
