# Generated by Django 2.2 on 2020-12-08 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_detai_tendetai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detai',
            old_name='TenDeTai',
            new_name='Ten',
        ),
    ]
