# Generated by Django 2.2 on 2020-12-08 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20201208_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detai',
            name='Ten',
        ),
    ]
