# Generated by Django 2.2 on 2020-12-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_detai_tendetai'),
    ]

    operations = [
        migrations.AddField(
            model_name='detai',
            name='DaDangKi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hoatdong',
            name='DaDangKi',
            field=models.IntegerField(default=0),
        ),
    ]
