# Generated by Django 2.2 on 2020-12-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20201208_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='detai',
            name='DangThuchien',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='hoatdong',
            name='DangThuchien',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
