# Generated by Django 2.2 on 2020-12-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20201208_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detai',
            old_name='DangThuchien',
            new_name='DangThucHien',
        ),
        migrations.RenameField(
            model_name='hoatdong',
            old_name='DangThuchien',
            new_name='DangThucHien',
        ),
        migrations.AlterField(
            model_name='hoatdong',
            name='IdGiaiThuong',
            field=models.IntegerField(default=0),
        ),
    ]
