# Generated by Django 2.2 on 2020-12-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20201208_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoatdong',
            old_name='IdGiaiThuong',
            new_name='DiemRL',
        ),
        migrations.AddField(
            model_name='detai',
            name='IdKhoa',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
