# Generated by Django 2.2 on 2020-12-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20201211_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='KHOA',
            fields=[
                ('IdKhoa', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('TenKhoa', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='loaidetai',
            name='DiemSan',
        ),
    ]
