# Generated by Django 2.2 on 2020-12-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20201211_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='Khoa',
            field=models.IntegerField(default=0),
        ),
    ]
