# Generated by Django 2.2 on 2020-12-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_dieukiendangky'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongbao',
            name='TieuDe',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
