# Generated by Django 2.2 on 2020-12-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_remove_thongbao_iduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoatdong',
            name='TenHoatDong',
            field=models.CharField(default='sda', max_length=1000),
            preserve_default=False,
        ),
    ]
