# Generated by Django 2.2 on 2020-12-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_hoatdong_tenhoatdong'),
    ]

    operations = [
        migrations.CreateModel(
            name='DIEMTRUNGBINH',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('Diem', models.FloatField(default=0)),
            ],
        ),
    ]
