# Generated by Django 2.2 on 2020-12-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_diemtrungbinh'),
    ]

    operations = [
        migrations.CreateModel(
            name='DIEMRENLUYEN',
            fields=[
                ('idDiem', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('userID', models.IntegerField()),
                ('Diem', models.FloatField(default=0)),
                ('Ki', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='hoatdong',
            name='Ki',
            field=models.IntegerField(default=1),
        ),
    ]
