# Generated by Django 2.2 on 2020-12-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_auto_20201220_1421'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DIADIEM',
        ),
        migrations.RemoveField(
            model_name='hoatdong',
            name='IdDiaDiem',
        ),
    ]
