# Generated by Django 2.2 on 2021-01-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_auto_20201220_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOAIHD',
            fields=[
                ('idLoaiHD', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('TenLoaiHD', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='hoatdong',
            name='Loai',
            field=models.IntegerField(default=1),
        ),
    ]
