# Generated by Django 2.2 on 2021-01-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_auto_20210101_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoatdongdadangky',
            name='DaChamDiem',
            field=models.IntegerField(default=0),
        ),
    ]
