# Generated by Django 2.2 on 2021-01-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_hoatdongdadangky_dachamdiem'),
    ]

    operations = [
        migrations.AddField(
            model_name='diemrenluyen',
            name='hoatDongId',
            field=models.IntegerField(default=0),
        ),
    ]
